### ISSUE TITLE
Missing plugin topics: snippets, textobj and other

### ISSUE THREAD

**Issue by kiryph** [mhinz/vim-galore#100]
I know that the list in https://github.com/mhinz/vim-galore/blob/master/contents/plugins.md should not become a list of all plugins: however, I consider following topics important enough to add them: 

1. Topic: **Snippets**
    - ultisnips
    - neosnippet
    - garbas/snipmate
    - xptemplate

2. Topic: **Surround**
   - surround.vim
   - https://github.com/machakann/vim-sandwich which supports more customization and visualrepeat.vim

3. Topic: **Textobjects**
   - targets
   - https://github.com/AndrewRadev/sideways.vim
   - see kana textobj-user: https://github.com/kana/vim-textobj-user/wiki

4. Topic: **Cycle**
   - https://github.com/tpope/vim-speeddating
   - https://github.com/bootleq/vim-cycle
   - https://github.com/AndrewRadev/switch.vim

IMHO following plugins should be added as well
- vis.vim (people often complain about ex commands that they do not work on visual-blocks)
- unimpaired.vim
- FastFold
- exchange.vim
- scriptease.vim
- repeat.vim
- visualrepeat.vim

ft-specific ones:
- https://github.com/vim-latex/vim-latex
- https://github.com/tmhedberg/SimpylFold

Feel free to reject it, but I hope, I have mentioned a few reasonable additions.

**Comment by mhinz** [comment]
Great list, thank you! I added _most_ of the suggestions. :-)
