### ISSUE TITLE
Guidelines on linking back to the original

### ISSUE THREAD

**Issue by lsrdg** [mhinz/vim-galore#107]
Not everyone will notice that a fork is merely a fork of a greater project.
[This commit](https://github.com/lsrdg/vim-galore/commit/bcbeb23f19efcf656fdd93cf1ab477d6b7526dfe) adds [this badge](https://img.shields.io/badge/Version-Original-blue.svg) to the Portuguese fork, but somehow it doesn't feel right...

Options considered so far:
- a note below the badges ("Vim-galore, by/at mhinz/vim-galore", in h2 or h3 maybe?)
- a new section with translation's notes, motivations, credits, terminology etc 
- a badge (in this case, any comments on the text/color/placement?)

**Comment by mhinz** [comment]
I think there are way too few translations so far. Thinking about a consistent back-linking format seems a bit overkill at this point, although I appreciate the idea. :-)

I like your approach of using a badge though. It's not intrusive and still fits in with the other translation badges. Using a different color for highlighting it makes sense.

If there will be another translation on Github, I'll suggest your approach for sure, but I think it's not worth "writing down" yet. :-)

**Comment by lsrdg** [comment]
> I think there are way too few translations so far. 

I like the "...so far" part (:

> It's not intrusive and still fits in with the other translation badges.

That's exactly what I'd been pondering about; but if it didn't feel intrusive, when you saw it, then it's probably ok.

> I think it's not worth "writing down" yet. :-)

Me too, but since the writing style is quite relaxed and clearly not formal (as the builtin documentation), I do think the readers deserve some kind of 'introduction'... the translation is exactly for people who are not able to read the original version. 

But again, maybe it's just as you said, let's wait for more translations before overkilling at this point. :P 

This issue should probably be closed now (and sorry for opening one for small details, but

**Comment by mhinz** [comment]
> sorry for opening one for such small details

Don't be! Any feedback is good feedback. :)

**Comment by Tiptipi** [comment]
Helló tudnekem segíteni
