### ISSUE TITLE
Empty content of "Standard plugins"

### ISSUE THREAD

**Issue by hobo-mts** [mhinz/vim-galore#122]
H4 "Standard plugins" before H4 "Why hjkl for navigation?" exists, but contains nothing.

**Comment by mhinz** [comment]
Hmm, I'm not sure what you mean.

Neither [Why hjkl for navigation?](https://github.com/mhinz/vim-galore/blob/d88225f844a991c0ebaa2d6d2e445281e70a4ffd/README.md#why-hjkl-for-navigation)
nor [Standard plugins](https://github.com/mhinz/vim-galore/blob/d88225f844a991c0ebaa2d6d2e445281e70a4ffd/README.md#standard-plugins) are empty.

Maybe you have an old local version?

**Comment by hobo-mts** [comment]
I got vim-galore-1.2.zip at 2018-01-21. And have this in README.md:

```
#### Easter eggs

...

#### Standard plugins

...

#### Why hjkl for navigation?
```

**Comment by mhinz** [comment]
This repo doesn't use releases anymore. `1.2` was the last release but was published over 2 years ago. You're missing out. :-)

If you really want to read it locally, use git to get the repo or download this zip: https://github.com/mhinz/vim-galore/archive/master.zip
