### ISSUE TITLE
Add plugin SimpylFold for folding of python code

### ISSUE THREAD

**Issue by kiryph** [mhinz/vim-galore#125]
IMHO [SimpylFold](https://github.com/tmhedberg/SimpylFold) is a better plugin for folding of python code than the listed plugin [braceless.vim](https://github.com/tweekmonster/braceless.vim).

Could you add [SimpylFold](https://github.com/tmhedberg/SimpylFold) to the section for the filetype python? Currently, this plugin has 288 stars on github.

```
- [SimpylFold](https://github.com/tmhedberg/SimpylFold)
```

I have tried braceless.vim for folding of python code. However, it has some quirks and bugs. On the positive side: the performance is really good due to the way the plugin generates folds.

- When opening a python file, `braceless.vim` will not define any folds on open. Therefore commands such as `zm`, `zM`, `zr`, and `zR` do not work immediately. This is documented in braceless.vim and is intended

   > Keystrokes such as |zM| and |zR| will only work on folds you have previously closed.

   You have to fold all root folds manually to activate folds!

- Incorrect fold levels are defined when closing all root folds in following circumstance:
![screen shot 2018-03-04 at 17 00 49](https://user-images.githubusercontent.com/371756/36947550-9fbd2bbe-1fcd-11e8-8ec0-73c4ac1120e9.png)

  The maximal foldlevel should be 3. This might be a bug and can possibly be fixed. Currently, this makes commands `zm` and `zr` not really useful.

- Foldtext for methods with a decorator show only the decorator, not the name of the method, which is not what I want:
![screen shot 2018-03-04 at 17 05 24](https://user-images.githubusercontent.com/371756/36947579-425ff39c-1fce-11e8-82f4-e07a192c7c51.png)

  Someone who uses this plugin could probably raise a feature request for braceless.vim.

- Another thing I like about SimpylFold that it does not fold if-blocks which I think is a good choice.  braceless.vim cannot be configured to do this as well.

**Comment by mhinz** [comment]
You make some very good points. I'll add it.

Thanks!
