### ISSUE TITLE
Add plugins nvim-completion-manager, vim-sleuth, and vim-matchup

### ISSUE THREAD

**Issue by kiryph** [mhinz/vim-galore#126]
Section Code Completion
```
- [nvim-completion-manager](https://github.com/roxma/nvim-completion-manager)
```
(908 stars)

Section Misc
```
- [vim-sleuth](https://github.com/tpope/vim-sleuth)
```
(728 stars)

Section Navigation/Text objects
```
- [vim-matchup](https://github.com/andymass/vim-matchup)
```

I know that `vim-matchup` has not many stars on github but it is quite new. IMHO, it represents a significant improvement of `matchit` and `matchparen` and therefore I can highly recommend it.

**Comment by mhinz** [comment]
- nvim-completion-manager is nvim-only, so it doesn't fit here. :]
- I have a love/hate relationship with vim-sleuth, because it I often got false positives in the past. I'll add it anyway. People should try for theirselves.
- Huh, didn't know about vim-matchup. Looks good! Will add.

**Comment by kiryph** [comment]
- nvim-completion-manger is not necessarily nvim-only:
https://github.com/roxma/nvim-completion-manager#requirements
- vim-sleuth: I guess mean by false positives that vim-sleuth did not properly detect the correct settings for 'shiftwidth' and 'expandtab'. Tim Pope mentions in the README.md that the plugin is not yet battle proof. Therefore, I understand your hesitation. Maybe one could point user to the project https://github.com/editorconfig/editorconfig-vim and https://github.com/sgur/vim-editorconfig. This is also advertised by the new book *Modern Vim* by Drew Neil.
- I am quite happy with vim-matchup and I hope others can see its value as well.
