### ISSUE TITLE
What you mean by '"lucius" colorscheme'?

### ISSUE THREAD

**Issue by hobo-mts** [mhinz/vim-galore#129]
Computer game? Or as https://en.wikipedia.org/wiki/Lucius? I don't understand clear.

**Comment by mhinz** [comment]
I guess you're talking about https://github.com/mhinz/vim-galore#cosmetic-changes-to-colorschemes

I mean any colorscheme that is named "lucius" and where `:echo colors_name` outputs "lucius". The point is that `autocmd ColorScheme lucius` only triggers if you do `:colo lucius` and not for any other colorscheme.

But yes, "lucius" is also a real colorscheme and can find it here: https://github.com/mhinz/vim-galore/blob/master/PLUGINS.md#colorschemes-1
