### ISSUE TITLE
Old online vimdoc (7.3)

### ISSUE THREAD

**Issue by hobo-mts** [mhinz/vim-galore#132]
Drew Neil in [What's new in 2nd edition](http://vimcasts.org/blog/2015/11/whats-new-in-practical-vim-2nd-edition/) wrote:

"In the 1st edition, I used the [online documentation published on sourceforge](http://vimdoc.sourceforge.net/htmldoc/index.html). This resource has not been updated since 2010, which wasn’t a big problem when the 1st edition came out. But in the 2nd edition, I have written about features that have been released with version 7.4 of Vim. I needed a more up to date version of the documentation online.

Luckily, I found [vimhelp.appspot.com](http://vimhelp.appspot.com/), a site published and maintained by Carlo Teubner. This is automatically updated for each patch release of Vim, so it’s always up to date."

**Comment by mhinz** [comment]
Thanks! ✨
