### ISSUE TITLE
Russian translation

### ISSUE THREAD

**Issue by hobo-mts** [mhinz/vim-galore#134]
I've finished %subj. Now I have more "issues":

1. Can I publish my translation?
2. How can I?..

Issues:

- I don't use Git any.
- I don't want to use Git.
- If I publish my translation on my site, it lost Vim syntax  highlighting.
- I've translated "galore" as "солянка" -- russian soup from anything is at home at a moment.

Can you help me?

**Comment by mhinz** [comment]
You can publish it anywhere as long as you say that it's a translation of the original document hosted at https://github.com/mhinz/vim-galore.

> I've translated "galore" as "солянка" -- russian soup from anything is at home at a moment.

Uhm, that doesn't make any sense to me. :) `vim-galore` is a name, perhaps you shouldn't translate it.

I'm not sure how else to help.

**Comment by mhinz** [comment]
Yeah, "parental guidance", because "sm" could also be the short form of "sadomasochism".

**Comment by hobo-mts** [comment]
**Блеат!** Ну, вы докатились! What now mean  "Use of the short form is rated PG"? It is as some memo from porno site? Sorry my English.

It's not for you. Sorry. But I don't beleave that words in `:h`

**Comment by hobo-mts** [comment]
Sorry. I've got excited. SM exists. "Gory details" in Perl-book -- too.

**Comment by hobo-mts** [comment]
It's live.

**Comment by mhinz** [comment]
I'm closing this, since it's no real issue. But feel free to ask further questions in here.

When you finish the translation, I can add its URL to this document.

**Comment by hobo-mts** [comment]
You are right. I will finish work at this week. And notice for you.
