### ISSUE TITLE
Russian translation released

### ISSUE THREAD

**Issue by hobo-mts** [mhinz/vim-galore#135]
Here: http://givi.olnd.ru/vim-galore/vim-galore-ru.html

**Comment by mhinz** [comment]
Awesome! That was pretty quick.

Thank you! ✨

**Comment by mhinz** [comment]
Yeah, I noticed that versioning doesn't really work for such kind of text document. Nevertheless I pushed v1.3 now.

**Comment by lsrdg** [comment]
Great! Link added to the Portuguese translation [here](https://github.com/lsrdg/vim-galore/commit/580faebee2807949fabcd8bfc1dedc6d83388e47). (:
