### ISSUE TITLE
Add new standard plugin cfilter distributed with vim 8.1.0311 (21.8.2018)

### ISSUE THREAD

**Issue by kiryph** [mhinz/vim-galore#138]
Plugin cfilter is not loaded by default. The plugin is placed in packpath `$VIMRUNTIME/pack/dist/opt/cfilter`.
Help can be found under `:h cfilter-plugin`  (only paragraph in doc/quickfix.txt, no separate help file).
Load plugin with `:packadd cfilter`.

**Comment by mhinz** [comment]
So far I only mentioned the standard plugins that get loaded by default, but I reworded the "standard plugins" section to mention optional plugins as well now.

Thanks!
