### ISSUE TITLE
formulation

### ISSUE THREAD

**Issue by Konfekt** [mhinz/vim-galore#144]
> On many occasions, Vim emits events. You hook into these events by using autocmds.

For a programmer, emitting an event might be a well-known operation, but for someone having less technical ideas about emissions and events, maybe a formulation such as "You can trigger an action after many events in Vim, such as a buffer being saved or Vim having started up, by so-called `autocmds`" rings more of a bell.

**Comment by mhinz** [comment]
Unfortunately the README is riddled with all kinds of bad wording. If I ever find the time, I should go through it from top to bottom and make all the needed corrections, but.. I don't find any time. :-)

So, thank you for pointing this out!
