### ISSUE TITLE
Introduction to VimL scripting

### ISSUE THREAD

**Issue by mhinz** [mhinz/vim-galore#3]

**Comment by wsdjeg** [comment]
I think learn vimscript the hard way is a good stuff for this issue,also can you open a issue like shougo/deoplete's evelopment announce

**Comment by mhinz** [comment]
Definitely.

I'll put it in the [resource section](https://github.com/mhinz/vim-galore/#additional-resources) in the meantime.

**Comment by wsdjeg** [comment]
I am readding the readme,it is very amazing

**Comment by mhinz** [comment]
I intend to create an own document for VimL scripting. Closing.
