### ISSUE TITLE
Use clipboard^=unnamed instead of clipboard=unnamedplus

### ISSUE THREAD

**Issue by romainl** [mhinz/vim-galore#34]
I honestly have no idea if that's a long standing bug (never worked in 5+ years) or if it's supposed to behave like it does but `set clipboard=unnamedplus` doesn't work on Mac OS X.

You should suggest `unnamed` instead as it works perfectly.

Also, `set clipboard=something` is not portable at all. The default value on Linux (`autoselect,exclude:cons\|linux`) should not be carelessly overridden with `=something` or have any other value appended to it with `+=something`.

The most portable value is thus:

    set clipboard^=unnamed

**Comment by mhinz** [comment]
1) `clipboard=unnamedplus` works for me. (Tested in iTerm2 and Terminal.app.) Nevertheless I'll rewrite it to suggest using `"*` in all cases but Unix, where `"+` should be used for clipboard.

2) You're totally right about using `^=` instead.

**Comment by mhinz** [comment]
How do you like the latest version?  https://github.com/mhinz/vim-galore#clipboard

**Comment by romainl** [comment]
All good!

**Comment by mhinz** [comment]
Thanks for your feedback, romainl!

**Comment by romainl** [comment]
You are very welcome ;-)
