### ISSUE TITLE
Mapleader

### ISSUE THREAD

**Issue by mahyarap** [mhinz/vim-galore#36]
Hi,
Recommending ';' as the leader key breaks its useful functionality. I use the 'f' key for fast navigation and ';' to repeat it. If you map the leader key to ';', you have to press it twice to find the next occurrence for the first time which is annoying. I strongly recommend using the space key as the leader key.
For instance:
http://superuser.com/questions/693528/vim-is-there-a-downside-to-using-space-as-your-leader-key

**Comment by wsdjeg** [comment]
I think it is based on the user himself,I do not change my leader, just using `\`

**Comment by mahyarap** [comment]
@wsdjeg Of course using the default key bindings causes no problem but on some keyboards, the location of \ is a bit awkward! In that case remapping would be a good idea!

**Comment by wsdjeg** [comment]
I know ,I a

**Comment by mhinz** [comment]
I changed the example to use  `<space>` and the wording to suggest that the user should use whatever he prefers.

I also added a sentence mentioning that `:nmap <leader>` will show all leader mappings with the `<leader>` resolved already, so it can be used to check the mappings.

:arrow_right:  [Mapleader?](https://github.com/mhinz/vim-galore#mapleader)

**Comment by wsdjeg** [comment]
greate work

**Comment by mhinz** [comment]
Thanks for the feedback!
