### ISSUE TITLE
History of Vim-like editors

### ISSUE THREAD

**Issue by mhinz** [mhinz/vim-galore#4]
- [ ] merge https://github.com/mhinz/editor-history
- [ ] http://www.moolenaar.net/vimstory.txt
- [ ] https://medium.com/@jovica/the-history-of-vim-b707758fb54f#.cu8jfuwq3
- [ ] include Neovim
- [ ] [ed intro](http://wolfram.schneider.org/bsd/7thEdManVol2/edtut/edtut.pdf)

**Comment by ladislas** [comment]
and maybe also talk about Neovim? I've been using on both osx and linux, remote and global, for the past 10 months with no major issues and it has replaced vim and macvim for me :)

**Comment by mhinz** [comment]
Noted!

**Comment by mhinz** [comment]
I'm closing this, since I plan to release an article on this on an upcoming website: vimmer.net
