### ISSUE TITLE
performance section suggestions

### ISSUE THREAD

**Issue by justinmk** [mhinz/vim-galore#56]
https://github.com/mhinz/vim-galore#editing-small-files-is-slow

- spelling: "Particulay"
- The presentation of Option:Why? table is confusing, because the left column presents `nofoo` options, then the right column explains why `foo` is slow
- regarding cursorline, relativenumber: per Bram, the reason they are slow is because they cause every line to redraw. source: https://groups.google.com/d/msg/vim_dev/bGtuqDXaUx0/Bb5PP3jnBQAJ

**Comment by mhinz** [comment]
I rewrote the whole section to make it clearer.

Thanks!
