### ISSUE TITLE
Plugin suggestions

### ISSUE THREAD

**Issue by arysom** [mhinz/vim-galore#58]
Some plugins propositions: 
- https://github.com/FredKSchott/CoVim
- https://github.com/flazz/vim-colorschemes
- https://github.com/junegunn/goyo.vim

**Comment by mhinz** [comment]
- Do you use `CoVim` from to time? It's supposed to be, well, experimental, but I haven't used it so far. It looks like they even think about moving to Neovim, https://github.com/FredKSchott/CoVim/issues/86. Do you happen to know the state of [floobits.vim](https://github.com/Floobits/floobits-vim)?
- The author doesn't seem very active and there are many open issues. I have to admit that I'd prefer suggesting (as in well-tested) [colorschemes](https://github.com/mhinz/vim-galore/#list-of-colorschemes-1) over such collections. :)
- I'll absolutely add goyo!

**Comment by mhinz** [comment]
Ok, I added CoVim and goyo, but not vim-colorschemes for the reason state above. :)

Thanks for the feedback!

**Comment by arysom** [comment]
* I was looking for some solution to learn kid programming, and it seemed interesting, but you're right - cooperative writing in vim isn't easy. Although there were some approaches http://usevim.com/2013/04/17/collaborative-vim/ - but it's too much. Never used floobits.
* You're right - it's better to promote certain colorschemes
* It's a kind of productivity plugin, popular subject these days
Great Work! I thank You!

**Comment by arysom** [comment]
*[drawit](http://www.vim.org/scripts/script.php?script_id=40) - make ascii art inside vim - exists as vimball but there is also pathogen version on github

**Comment by arysom** [comment]
Not especially plugins but...
-[tetris](http://www.vim.org/scripts/script.php?script_id=172)
-[sokoban](http://www.vim.org/scripts/script.php?script_id=211)

Also a word about games - there is vim-adventures.com game to learn vim(maybe commercial stuff, but maybe worth a mention)

**Comment by mhinz** [comment]
Hmm, drawit is not in interesting enough and the games were last updated in 2002. And yup, when I played vim-adventures years ago, you could only do so for some minutes before they wanted you to pay.

**Comment by arysom** [comment]
[calendar](https://github.com/itchyny/calendar.vim) - for time managment

**Comment by wsdjeg** [comment]
@arysom will you put all your work into vim?

**Comment by mhinz** [comment]
@arysom Okay, I added calendar because it's technically interesting and shows what can be done with Vim.

**Comment by arysom** [comment]
@wsdjeg I've heard that some people rarely move outside their text editor, but I'm not that type.

**Comment by wsdjeg** [comment]
@arysom with the help of this repo,I think I can move most of my work into neovim in the future, but now I can not ,because I need terminal ,and I am not very familiar with neovim's terminal

**Comment by arysom** [comment]
[vim table mode](https://github.com/dhruvasagar/vim-table-mode/) - make tables with... formulas

**Comment by arysom** [comment]
[https://github.com/dhruvasagar/vim-dotoo](vim-dotoo) - from the same author as above, more than to do list, personal agenda, time managment tool

**Comment by mhinz** [comment]
I added dotoo (for the moment.. et's see if he ever tackles its issues) and orgmode.

Enough plugins for now. Honestly, the list should give first pointers to newbies, not listing every single plugin out there. :-)

Thanks!
