### ISSUE TITLE
Usage of ```viml vs ```vim

### ISSUE THREAD

**Issue by george-b** [mhinz/vim-galore#71]
Both tpope's markdown.vim and github support the usage of

```
 ```vim
```

as opposed to

```
 ```viml
```

to syntax highlight code blocks of vim language. Would you be open to a pull request?

**Comment by wsdjeg** [comment]
```vim
```vim 
let g:ws = 11
```
```viml
```viml
let g:wsd = 11
```

**Comment by george-b** [comment]
When reading in vim yes, although I'm actually using neoivm but I don't think this makes a difference.

**Comment by wsdjeg** [comment]
I am using neovim ,and I can not find syntax highlight
![2016-01-22 21 50 15](https://cloud.githubusercontent.com/assets/13142418/12512267/3985bcca-c152-11e5-8c64-54db79a267a1.png)

**Comment by george-b** [comment]
You'll need to define `g:markdown_fenced_languages`, for example I have the following.

```vim

let g:markdown_fenced_languages = [
  \ 'c',
  \ 'vim',
  \ 'sh',
  \ 'ruby',
  \ 'python',
  \ 'yaml',
  \ 'sql',
  \ ]
```

**Comment by wsdjeg** [comment]
sorry,I do not us markdown plugin

**Comment by mhinz** [comment]
@wsdjeg The plugin is just the development version of the same files included in Vim. Even without the plugin you can use `let g:markdown_fenced_languages = ['vim']`.

@george-b I'd appreciate a PR!

**Comment by wsdjeg** [comment]
thanks @mhinz I got it

**Comment by george-b** [comment]
Created PR #73
