### ISSUE TITLE
Quickly add empty lines

### ISSUE THREAD

**Issue by springcold** [mhinz/vim-galore#75]
`Quickly add empty lines

This is surely no must-have, but I prefer the following mappings over o<esc>/O<esc>:

nnoremap [<space>  :put! =''<cr>
nnoremap ]<space>  :put =''<cr>`

It seems that o<esc> can accept a count to increase by the number of count but not :put
Maybe you would like to reconsider?

**Comment by wsdjeg** [comment]
but o/O will sent a enter  insert event.sometime there is no need switch to insert model

**Comment by springcold** [comment]
Seems valid from both point, I guess it will depend on user themselves whether they need to insert with multi-count or not and whether they use the event function you mentioned

**Comment by springcold** [comment]
Come to think of it, it may not be that frequent to need to add a lot of empty lines

**Comment by wsdjeg** [comment]
I just tell you the diff between o/O and `:put`.
same as the vim-galore,we just tell you how to do,we do not tell you must to do anything.
You need to decide how to choose yourself！

**Comment by mhinz** [comment]
@springcold You're right as in the mappings should have taken a count from the beginning. They do now!
