### ISSUE TITLE
"Edit macros" map

### ISSUE THREAD

**Issue by desjardinsm** [mhinz/vim-galore#78]
I'm not sure if this is significant enough to consider, but:

In the map [to edit your macros](https://github.com/mhinz/vim-galore#quickly-edit-your-macros), if that macro contains a `<c-r>`, then when the expression register of the map is evaluated, the control-r gets replaced with the current contents of that register instead of being left as-is.  You can workaround that with a `substitute()` but it's a bit ugly.

**Comment by mhinz** [comment]
Nicely spotted! Actually, Vim got us covered here: `:h c_^R^R`.

**Comment by mhinz** [comment]
Thanks for noticing!

**Comment by desjardinsm** [comment]
Oh...I knew about c_^R^R, was actually part of my solution.  I just derped and didn't think to add it to the expression register itself...
