### ISSUE TITLE
Intro

### ISSUE THREAD

**Issue by mhinz** [mhinz/vim-galore#8]
- [x] What is Vim?
- [x] Philosophy
- [x] First steps
- [x] Stress to learn the basics before adding loads of plugins that only do the same anyway
- [x] Minimal vimrc with comments
- [x] Cheatsheets
- [x] Key representation (added to the related help in the mappings section)

**Comment by mhinz** [comment]
Mention:

- [ ] `vimtutor`
- [ ] Stress to learn the basics before adding loads of plugins that only do the same anyway
- [ ] Link to minimal vimrc

**Comment by kevinSuttle** [comment]
I would start even sooner. Many newcomers don't know what Vim is, why it's different, or where/how to download/install it. Assuming that they already do is a stumble out of the gate in my opinion.

**Comment by mhinz** [comment]
You're right. I'll add it today.

**Comment by mhinz** [comment]
I pushed a first draft.

**Comment by kevinSuttle** [comment]
Awesome! Great job.

**Comment by mhinz** [comment]
All done!

**Comment by kevinSuttle** [comment]
:+1:
