### ISSUE TITLE
Add agit and yowish colorscheme

### ISSUE THREAD

**Issue by KabbAmine** [mhinz/vim-galore#82]
Please consider adding the following plugins:
- [Agit](https://github.com/cohama/agit.vim): A gitk clone for Vim quicker than [gitv](https://github.com/gregsexton/gitv) and more customizable than [gv](https://github.com/junegunn/gv.vim).  
- [Yowish](https://github.com/kabbamine/yowish.vim): A dark colorscheme that looks good in many file types (My plugin).

**Comment by mhinz** [comment]
Done! Thanks for the suggestions.
