### ISSUE TITLE
add `autocmd ColorScheme` info

### ISSUE THREAD

**Issue by mmlb** [mhinz/vim-galore#88]
@mhinz dropped [this](https://gitter.im/neovim/neovim?at=575887e82eaa837d71e79fa0) piece of info so casually but it is great and should be added to vim-galore.

Where to put though?
- `ColorSchemes` - makes sense because users can be expected to want to tweak a couple of things in colorschemes

- `Autocmds` - is pretty nice because it hints at another class of filetypes that vim recognizes (I always just thought it was by `ft`)

- `Tips` - because it is a minor bit of info.

**Comment by mhinz** [comment]
Hi, I wanted to keep it as short as possible, so I put it into the Tips section, but also added a link to it from the Basics section, where the usage of `:hi` is explained etc.

Thanks for bringing this up!
